
----------------------------------------------------- Database Exploration -----------------------------------------------------------------------------------
-- Explore All Objects In the Database
USE DataWarehouseAnalytics
GO
SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- Explore all the columns in the database
select * from INFORMATION_SCHEMA.COLUMNS


-----------------------------------------------------DIEMENSION EXPLORATION-------------------------------------------------------------------
-- Explore all countries where our customers come from
select distinct country from gold.dim_customers

-- Explore all categories "The major divisions"
select distinct category, subcategory, product_name from gold.dim_products
order by 1,2,3


-----------------------------------------------------DATE EXPLORATION------------------------------------------------------------------------------
--find the date of the first and last order
--How many years of sales are available

select min(order_date) as first_orderDate,
max(order_date) as last_orderDate,
DATEDIFF(year,min(order_date),max(order_date)) as order_range_years
from gold.fact_sales

-- find the ypongest and oldest customer
select min(birthdate) as oldest_birthday , 
datediff(year, min(birthdate), GETDATE()) as oldest_age,
max(birthdate) as youngest_birthday, datediff(year, max(birthdate), GETDATE()) as youngest_age
from gold.dim_customers

-------------------------------------------------MEASURE EXPLORATION------------------------------------------------------------------------------
-- find the total sales
select sum(sales_amount) as total from gold.fact_sales

-- find how many items are sold
select count(quantity) as total_item from gold.fact_sales

-- find the average selling price
select avg(price) as avg_seling_price from gold.fact_sales

-- find total numbers of orders
select count(order_number) as total_order from gold.fact_sales
select count(distinct order_number) as total_order from gold.fact_sales

-- find total number of products
select count(product_key) as total_product from gold.dim_products

-- find total numbers of customers
select count(customer_key) as total_customer from gold.dim_customers

-- find total numbers of customers who has placed an order
select count(distinct customer_key) as total_customer from gold.fact_sales

--Generate a report that shows all the key matric of the business
select 'Total Sales' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union all
select 'Total quantity' as measure_name, count(quantity) as measure_value from gold.fact_sales
union all
select 'Average Price' as measure_name, avg(price) as measure_value from gold.fact_sales
union all
select 'Total Order',count(distinct order_number) from gold.fact_sales
union all
select 'Total Product',count(product_key) from gold.dim_products
union all
select 'Total Customer',count(customer_key) as total_customer from gold.dim_customers

------------------------------------------------------MAGNITUDE EXPLANATION-----------------------------------------------------------------------------
--find total number of customers by country
select country, count(customer_key) as total_customers from gold.dim_customers
group by country
order by  total_customers desc

-- Find total customers by gender
Select gender,COUNT(customer_key) AS total_customers 
from gold.dim_customers
group by gender
order by total_customers desc;

-- Find total products by category
select category, COUNT(product_key) AS total_products
from gold.dim_products
group by category
order by total_products desc;

-- What is the average costs in each category?
select category,AVG(cost) AS avg_cost
from gold.dim_products
group by category
order by avg_cost desc;

-- What is the total revenue generated for each category?
select p.category,SUM(f.sales_amount) AS total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_products p  on p.product_key = f.product_key
group by p.category
order by total_revenue desc;

-- What is the total revenue generated by each customer?
select c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount) AS total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_customers c ON c.customer_key = f.customer_key
group by c.customer_key, c.first_name,c.last_name
order by total_revenue desc;


-- What is the distribution of sold items across countries?
select  c.country, SUM(f.quantity) AS total_sold_items 
from gold.fact_sales f LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
group by c.country
order by total_sold_items desc;

---------------------------------------------------RANKING ANALYSIS-----------------------------------------------------------------------------------------
-- Which 5 products Generating the Highest Revenue?
select *
from (
    select
        p.product_name,
        SUM(f.sales_amount) AS total_revenue,
        RANK() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
    from gold.fact_sales f
    LEFT JOIN gold.dim_products p
        on p.product_key = f.product_key
    group by p.product_name
) AS ranked_products
where rank_products <= 5;

-- What are the 5 worst-performing products in terms of sales?
select TOP 5
    p.product_name,
    SUM(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_products p
    on p.product_key = f.product_key
group by p.product_name
order by total_revenue;

-- Find the top 10 customers who have generated the highest revenue
select TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
    on c.customer_key = f.customer_key
group by
    c.customer_key,
    c.first_name,
    c.last_name
order by total_revenue desc;

-- The 3 customers with the fewest orders placed
select TOP 3
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(distinct order_number) as total_orders
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
    on c.customer_key = f.customer_key
group by
    c.customer_key,
    c.first_name,
    c.last_name
order by total_orders ;













